export const GET_VIDEOS = "GET_VIDEOS";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL";
export const GET_VIDEO_COMMENTS = "GET_VIDEO_COMMENTS";
export const GET_VIDEO_COMMENTS_SUCCESS = "GET_VIDEO_COMMENTS_SUCCESS";
export const GET_VIDEO_COMMENTS_FAIL = "GET_VIDEO_COMMENTS_FAIL";
export const SELECT_VIDEO = "SELECT_VIDEO";
